### ISSUE TITLE
index.js try catch

### ISSUE THREAD

**Issue by 2vitor** [gbrsrs/bottemplate#1]
a função createCore deveria virar assíncrona e utilizar apenas o método catch. (<promise>.catch(...))

```
try {
  createCore(...)
[...]
```

**Comment by 2vitor** [comment]
-- também transformado toda a função core em async (por exemplo, readdir deixará de ser Sync)

**Comment by gabrieljesusdev** [comment]
Kkkkk, muito obrigado.

Irei fazer essas melhorias, obrigado por contribuir com meu conhecimento.
Fico grato de verdade, :)

Em qui, 25 de mar de 2021 23:34, 2vitor ***@***.***> escreveu:
